spring:
  datasource:
    url: jdbc:mysql://192.168.1.207:3306/sells?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
      show-sql: true
server:
  servlet:
    context-path: /sells