spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sells?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
server:
  servlet:
    context-path: /sells